title = "Home"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "My World of Poetry.."
  facebook = "https://www.facebook.com/roopika.tandon"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  commentoEnable = true
  gitlab = ""
  linkedin = ""
  mastodon = ""
  body_classes = "corona bg-white"
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/wall.jpg"
  recent_posts_number = 4
